### ISSUE TITLE
Kubernetes Tutorial doesn't run

### ISSUE THREAD

**Issue by sysarcher** [AntonioMeireles/ClearLinux-packer#11]
Hi @AntonioMeireles ,

There's a tutorial to [run k8s on Clearlinux](https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes) from Clearlinux team. 

I haven't been able to successfully run `kubeadm init ...` on this box. The `Vagrantfile` that I'm using is here: https://github.com/shrmrf/k8s-resources/blob/master/clear/Vagrantfile

The run log is here: https://github.com/shrmrf/k8s-resources/tree/master/clear#problems

I am not sure if this is a problem with this box or with the tutorial... or with Clearlinux? Any ideas? Tips?

**Comment by AntonioMeireles** [comment]
@shrmrf 

hi again, 

sorry lag. definitively k8s work on top of CL. i've made a full featured k8s install/maintenance tool specific to CL that works both on top of Vagrant and  bare-metal... i expect to have it public some time in the future once fully cleaned up. 

if you're in a hurry please mail me off line :-)

**Comment by sysarcher** [comment]
@AntonioMeireles ahh, cool!!

I'll send you an email offline then :)

Thanks again for the great tools you're producing. (I'll close this issue as it's not related to your Vagrant box)
