### ISSUE TITLE
Can't run Docker in Latest Box

### ISSUE THREAD

**Issue by sysarcher** [AntonioMeireles/ClearLinux-packer#13]
I can't seem to run docker containers in the latest box:

```console
clear@clearlinux ~ $ docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.                                                                                                         
See 'docker run --help'.
clear@clearlinux ~ $ sudo docker run hello-world                                                                                                                                                                   
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.                                                                                                         
See 'docker run --help'.
```

This problem does not happen with version `25700` (the one I had already)

**Comment by AntonioMeireles** [comment]
Hi again! 

It's not a *bug*, more a _feature_ of sorts. Latest box started masking docker service by default (see [here](https://github.com/AntonioMeireles/ClearLinux-packer/pull/12) for context.

To get it back just `sudo systemctl unmask docker && sudo systemctl enable docker --now`. 
Also, if you happen to be using the `vagrant-proxyconf` plugin (as most at Intel seem to be forced to) you 'd also need to add to your Vagrantfile the following snippet: 
```ruby
  if Vagrant.has_plugin?('vagrant-proxyconf')
    config.proxy.enabled = { docker: true }
  end 
```

AFAICT this should be enough to get things working for you :-) 

All the best, 

António

**Comment by sysarcher** [comment]
Hey Antonio, thanks for that!! I think i came back after a loooong time to Clearlinux. Will try and let you know!! I'll close the issue.
