### ISSUE TITLE
Would it be possible to support vagrant 2.1.2?

### ISSUE THREAD

**Issue by gblewis1** [AntonioMeireles/ClearLinux-packer#15]
Vagrant 2.1.2 comes with Fedora 29 and works well with it. I have an issue with rsync when I manually upgrade to Vagrant 2.2.4 on that OS.  When running with Vagrant 2.1.2:

This Vagrant environment has specified that it requires the Vagrant
version to satisfy the following version requirements:

 " >= 2.1.5"

**Comment by gblewis1** [comment]
Tried with Vagrant 2.1.5 and got the same issue with rsync on Fedora 29:

Error: rsync: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
rsync error: syntax or usage error (code 1) at main.c(1578) [server=3.1.3]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]

**Comment by AntonioMeireles** [comment]
Hi, 

> Tried with Vagrant 2.1.5 and got the same issue with rsync on Fedora 29:
> 
> Error: rsync: This rsync lacks old-style --compress due to its external zlib. Try -zz.
> rsync error: syntax or usage error (code 1) at main.c(1578) [server=3.1.3]
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]
 
Oh, *that*... 

it's not Vagrant fault ... it's a side effect (on recent box versions) of https://github.com/clearlinux/distribution/issues/488 (still not solved) :( in the meantime do the workaround here - https://github.com/clearlinux/cloud-native-setup/commit/c2e932ac7b9b51263a910f6417c319a84429a83d#diff-f334f661cd44abe3d9e8b8a99fbd2b27 - as it should get you past this  (if i'm mistaken and that does not solve the issue get back to bug me) 

I've not come in the meantime with a clean way to do it my side (guest plugin) with a transparent workaround that works with old and new rsync styles :-/ 

Thanks for caring/reporting and have a great weekend!

All the Best, 

António 
//cc @ganeshmaharaj

**Comment by gblewis1** [comment]
Oh, interesting. I hadn't considered that it might be a function of the guest OS.  That workaround works for now with 2.1.5, so I'll go with it. Thank you for the prompt response!

**Comment by AntonioMeireles** [comment]
@gblewis1 

going to close this... feel free to get back if you have any additional needs :-) 

Have a great weekend && thanks for your patience!
