### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by sysarcher** [AntonioMeireles/ClearLinux-packer#2]
When I do `vagrant up` I get the following on Ubuntu 16.04

```
Unable to resolve dependency: user requested '{:name= (> 0)'         
Bundler, the underlying system Vagrant uses to install plugins,      
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network    
issues. The error from Bundler is:                                   
```

I have no idea what this means.

Vagrantfile [used directly from Vagrant Cloud](https://app.vagrantup.com/AntonioMeireles/boxes/ClearLinux/versions/22880):
```rb
Vagrant.configure("2") do |config|
  config.vm.box = "AntonioMeireles/ClearLinux"
  config.vm.box_version = "22880"
end
```

**Comment by AntonioMeireles** [comment]
odd. whith vbox or vmware ? (thannks for reporting and for your patience!)

**Comment by sysarcher** [comment]
@AntonioMeireles I'm using Virtualbox.

I think I figured out that I was missing the plugin...?? (It's not documented perhaps?)

```
vagrant plugin install vagrant-guests-clearlinux
```

I can boot now!

**Comment by AntonioMeireles** [comment]
ok, my fault anyway .. will try to get better docs as soon as i have spare time :-) 

(patches welcome btw ;-) )  

THANKS!

**Comment by sysarcher** [comment]
I'll send out a pull request soon!! Thanks for the box though 👍 (closing the issue)
