### ISSUE TITLE
Question: how to control the existing network interface?

### ISSUE THREAD

**Issue by beckend** [AntonioMeireles/ClearLinux-packer#23]
Would like to use my custom network interfaces, and not the existing one, don't want or need it to access internet.

**Comment by beckend** [comment]
Using libvirtd I get this:
```shell
lspci | egrep -i --color 'network|ethernet'
07:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
```

**Comment by beckend** [comment]
found relation to: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1057

**Comment by AntonioMeireles** [comment]
@beckend 

could you please elaborate a bit more about what you are trying to achieve ?  (not sure i'm understanding)

**Comment by beckend** [comment]
No access to the internet on the current network device

**Comment by beckend** [comment]
found out about `libvirt.mgmt_attach = false`
