### ISSUE TITLE
Vagrant script is broken on latest Clearlinux (33590)

### ISSUE THREAD

**Issue by namm2** [AntonioMeireles/ClearLinux-packer#25]
Hi, I've tried to use your script to setup vagrant on Clearlinux 33590 but seems like the Clearlinux's ruby version is incompatible with vagrant.

```
/tmp/vagrant-2.2.9 /home/nam/cloud-native-setup/clr-k8s-examples
  Successfully built RubyGem
  Name: vagrant
  Version: 2.2.9
  File: vagrant-2.2.9.gem
Successfully installed pkg-config-1.4.1
ERROR:  Error installing vagrant-2.2.9.gem:
	There are no versions of vagrant (= 2.2.9) compatible with your Ruby & RubyGems
	vagrant requires Ruby version ~> 2.4, < 2.7. The current ruby version is 2.7.1.83.
1 gem installed

```

```
swupd info  
Distribution:      Clear Linux OS
Installed version: 33590
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
```

I'm not sure this is a right place to post this issue.

**Comment by AntonioMeireles** [comment]
Hi, 

Just pushed a patch to my custom vagrant installer in order for it to tolerate ruby-2.7.* until upstream gets it sorted. try again plz and confirm that things now work again as expected.  (on my quick testing they do - *but* i'm vacation in the middle of nowhere with very limited connectivity so YMMV)  

thanks for reporting!

All the best,

**Comment by AntonioMeireles** [comment]
closing per above. @namm2 please reopen this if issue reemerges. 

have a great weekend!
