### ISSUE TITLE
New Build with Clear Linux OS 34090

### ISSUE THREAD

**Issue by mdhorn** [AntonioMeireles/ClearLinux-packer#26]
@AntonioMeireles Would it be possible to kick off a new build with the 34090 release?
We have updated the version of several packages for Kubernetes and an early update would be super helpful.
Or point me to the sets up help make the update.

**Comment by AntonioMeireles** [comment]
@mdhorn 

**hey**!, 

**sure it is**!.  

just pushed `34090` boxes for virtualbox and libvirt. QA was minimal, due to lack time (a bit late here 😄 as 2am). 

Please report if issues arise. (you can mail me directly if you prefer - address the one in the git commit logs)   

All the best, 

António

**Comment by mdhorn** [comment]
Thank you for the quick response!
