### ISSUE TITLE
Increase hard drive space?

### ISSUE THREAD

**Issue by sysarcher** [AntonioMeireles/ClearLinux-packer#4]
Hi @AntonioMeireles 

Right now, the rootfs is around 9.7G which is fairly small for developing on clearlinux I guess (especially if you have the `os-clr-on-clr` bundle installed.)

Can we increase the default size to upwards of 40G? 

I tried to look around but since I don't have any expertise in `packer`, didn't find anything really. Also, it seems that the `Makefile` is looking for Vmware to be present on the host machine for building which I don't have.

**Comment by sysarcher** [comment]
Hi @AntonioMeireles I was looking into the sources and it seems that the only dependency on vmware is [while creating the hard drive](https://github.com/AntonioMeireles/ClearLinux-packer/blob/master/Makefile#L22)

Would it make sense to replace this line with an equivalent Virtualbox command?

**Comment by AntonioMeireles** [comment]
@shrmrf 

First things fist - sorry lag replying && thanks for reporting! 
regarding your points: 
a) latest box iteration (23090 that just got in) is 40G in size per your request. 
b) re: the dep in vmware-vdiskmanager. will take a look (OTOH patches are welcome ;-) )

FWIW another thing that is in my radar is improve the Makefile to be cross-platform. right now is a bit MacOS / homebrew centric ... 

Feel free to bug me for extra features/reports/sugestions! 

Best Regards and have a great weekend!

**Comment by sysarcher** [comment]
@AntonioMeireles cool... I'm testing this box on Linux. Thanks for the 40G box as well 👍 

I'll check if Virtualbox's `vboxmanage` command can replace the `vmware-vdiskmanager` and do the exact equivalent. Will let you know. And thanks again for increasing the box size. I was doing shenanigans like mounting an extra hard drive and remounting `/var` to the new hard drive. Hopefully, no more!!
