### ISSUE TITLE
RFE:  Add the "editors" bundle

### ISSUE THREAD

**Issue by kvietmeier** [AntonioMeireles/ClearLinux-packer#5]
Thanks for maintaining this Vagrant box repo!

A suggestion to improve it-
 
As currently configured the Vagrant box doesn't have any editors installed which makes it hard to do anything if you can't add them from a Vagrantfile or after a startup when no network is present or proxies are blocking you..

Starting build - 
```
clear@clearlinux ~ $ sudo swupd bundle-list
swupd-client bundle list 3.15.3
   Copyright (C) 2012-2018 Intel Corporation

bootloader
kernel-native
network-basic
openssh-server
os-core
os-core-update
perl-basic
python3-basic
storage-utils
sysadmin-basic
```

I found this to be a good basic set of additional tools for baseline system:
```
dev-utils 
editors 
perl-basic 
shells
```

Which results in:
root@clearlinux ~ # swupd bundle-list
```
bootloader
dev-utils
editors
emacs
ethtool
git
iproute2
joe
kernel-native
network-basic
openssh-server
openssl
os-core
os-core-update
p11-kit
perl-basic
python3-basic
shells
storage-utils
sudo
sysadmin-basic
vim
which
wpa_supplicant
```

Regards,

**Comment by AntonioMeireles** [comment]
(sorry latency). `nano` is there already, actually. anyway you raise valid points, being that the tricky question is to spot the right balance in order not to make the box too fat. i'll add for now `editors` and `shells` and wait for further feedback until adding more stuff . 

thanks again for your very valuable feedback!

**Comment by AntonioMeireles** [comment]
@kvietmeier [v23240](https://app.vagrantup.com/AntonioMeireles/boxes/ClearLinux/versions/23240) box consumes already commit above.

**Comment by kvietmeier** [comment]
Ah the "editor wars", many of us look for vi/vim first :)

Just booted up the latest version - all there thanks!  

I needed the editor because I couldn't install software from behind my proxies without editing a file first.

BTW - Would love to collaborate - you can email me.

**Comment by sysarcher** [comment]
@kvietmeier / @AntonioMeireles one of you should close this issue :) 

reflects badly on Antonio's rapid responses to all issues

**Comment by AntonioMeireles** [comment]
done...

**Comment by kvietmeier** [comment]
We did leave it open too long - sorry.

**Comment by AntonioMeireles** [comment]
(thinking loud) in order to keep default box sizes reasonable (and corresponding download times) for people on slow links would it be unreasonable to **stop** shipping the whole `editors` bundle (which contains `emacs`, `vim` and `joe` bundles) and just ship by default instead **only** the `vim` bundle ?

**Comment by sysarcher** [comment]
Yup!! Totally reasonable IMO

**Comment by kvietmeier** [comment]
Yes.   Completely agree.  This is reason I'm not a big fan of the bundles.

**Comment by AntonioMeireles** [comment]
done.
