### ISSUE TITLE
ponder changing to linux-lts kernel for VirtualBox guests

### ISSUE THREAD

**Issue by AntonioMeireles** [AntonioMeireles/ClearLinux-packer#7]
@shrmrf @kvietmeier

Do you have any sort of objections to change the default shipping kernel on the VirtualBox boxes to `linux-lts` one, in order, to consume the vbox guest kmods? (per the _upstream_ recommendations [here](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox))

On paper, should improve perf a bit :-) 

&& **Thanks**!

**Comment by sysarcher** [comment]
@AntonioMeireles no.. in fact the clearlinuxes I build always use the `linux-lts` kernel. (I build it for embedded devices). You have my vote 👍

**Comment by kvietmeier** [comment]
@AntonioMeireles - No objection here, sounds like the right thing to do.

**Comment by AntonioMeireles** [comment]
could you both give a look plz, when with some spare time, at 
[23950](https://app.vagrantup.com/AntonioMeireles/boxes/ClearLinux/versions/23950) and see if nothing broke ? :-)

**Comment by sysarcher** [comment]
@AntonioMeireles will update you by this time tomorrow!

**Comment by sysarcher** [comment]
@AntonioMeireles the latest box doesn't seem to boot for me...

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by AntonioMeireles** [comment]
oopss. gonna look asap, after my lunch break. *THANKS!*

**Comment by AntonioMeireles** [comment]
can you try again plz ? (uninstall and reinstall 23950 box - should be fixed now, at least seems to work here)

**Comment by sysarcher** [comment]
@AntonioMeireles I'm getting the following error:

I checked that I have the `vagrant-guests-clearlinux` plugin installed.

```
$ vagrant up --no-provision
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested '{:name= (> 0)'
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested '{:name= (> 0)'
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested '{:name= (> 0)'
```

**Comment by AntonioMeireles** [comment]
a naked box 
```
Vagrant.configure("2") do |config|
  config.vm.box = "AntonioMeireles/ClearLinux"
end
```
works ok here 

```
❯❯❯ vup --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'AntonioMeireles/ClearLinux'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: x_default_1532616845318_42998
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: clear
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: [vagrant-dns] TLD but no host_name given. No patterns will be configured.
vagrant-dns: trying to stop process with pid 31278...
vagrant-dns: process with pid 31278 successfully stopped.
vagrant-dns: process with pid 31928 started.
==> default: Restarted DNS Service
==> default: Setting hostname...
```
```
❯❯❯ vssh default
clear@clearlinux ~ $ uname -a
Linux clearlinux 4.14.34-382.lts #1 SMP Sun Apr 15 17:59:40 UTC 2018 x86_64 GNU/Linux
clear@clearlinux ~ $ ifconfig 
enp0s17   Link encap:Ethernet  HWaddr 08:00:27:24:AA:D1  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe24:aad1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:880 errors:0 dropped:0 overruns:0 frame:0
          TX packets:643 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:84041 (82.0 Kb)  TX bytes:78468 (76.6 Kb)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:78 (78.0 b)  TX bytes:78 (78.0 b)

clear@clearlinux ~ $ 
```

can you provide the Vagrantfile that is failing ?

**Comment by sysarcher** [comment]
I did the following steps:-
```
$ vagrant init AntonioMeireles/ClearLinux
  ...
$ vagrant plugin list
  vagrant-guests-clearlinux (1.0.9)

$ vagrant up
  ...
```

So, it's the default `Vagrantfile` that is autogenerated by `vagrant`

Let me try to use an older version of the box.

**Comment by AntonioMeireles** [comment]
oh ... `vagrant plugin update` will get you 1.0.10 ... and _then_ (fingers crossed) things should behave. need to find why the erros messages are so ... undescriptive ...

**Comment by sysarcher** [comment]
Older version works... Let me update the plugin :)

@AntonioMeireles Yup!! Updating the plugin worked for me.. 

Thanks!!! I'll drill down into the gritties tomorrow and let you know.. 

THANKS AGAIN!

**Comment by sysarcher** [comment]
@AntonioMeireles I think you can close this issue. 
Looks good (i.e. if you were waiting for my feedback)!!

**Comment by AntonioMeireles** [comment]
@shrmrf 

i was, actually ;-) Good to know. Anything else in need to polish, BTW ? 

&& **thanks!**

**Comment by sysarcher** [comment]
I have pushed your box in my organization, and let's see :) I am pretty happy atm.

**Comment by kvietmeier** [comment]
I finally got time to test this.

I learned a few versions ago to always update the plugin when I update the box (I call this out in the README for my Vagrant environment).   I forgot, and rather than errors, "vagrant up" returned nothing.    

Didn't do any extensive testing but after updating the plugin, everything came up fine.

Not sure what was changed but previous to this version interfaces were not being created for my private networks.   I am now seeing 3 interfaces as expected.

**Comment by AntonioMeireles** [comment]
@kvietmeier 

FWI, for context,  regarding the plugin thing it was a mix of two things: a bug on my side and, on top of it, a Vagrant regression. Both handled in https://github.com/AntonioMeireles/ClearLinux-packer/commit/663230c0e19fb2e9466e3fc83408ae731fc8b366

regarding the network interfaces part, it was a bug in the VBox side... as the additional NICs (besides the 1st/internal one) weren't being created in advance (fixed by https://github.com/AntonioMeireles/ClearLinux-packer/commit/499d3d43f1776121cd7a5d79bb8b3210d99f1eca) 

I'm trying lately to have reasonable changelogs as the box seems to be gaining some traction ;-)   


Thanks for the feedback!

**Comment by sysarcher** [comment]
@AntonioMeireles with the new Mixer `v5.x.x`, you can't easily get started with using that tool unless you have `docker` installed on your system (unless one is aware of the `--native` flag which isn't discussed anywhere in the docs). 

This inevitably means that users will get frustrated and install a VM that works. I usually tell colleagues to try out your Vagrant box.

**Comment by sysarcher** [comment]
@kvietmeier can't Intel give this box their official blessing?

**Comment by AntonioMeireles** [comment]
@shrmrf - we'll ship docker from now on (**[v24240](
https://app.vagrantup.com/AntonioMeireles/boxes/ClearLinux/versions/24240)**, just out, already has it ~~will be public in a bit~~). regarding the other issue, ball not in my court, but glad to hear that this *may* end being up to Intel standards :-)

**Comment by sysarcher** [comment]
@AntonioMeireles if you added containers by default into the VM due to the Mixer tooling comment I made upstairs, they have been added as a dependency already in the mixer bundle https://github.com/clearlinux/clr-bundles/blob/master/bundles/mixer#L6

>regarding the other issue, ball not in my court, but glad to hear that this may end being up to Intel standards :-)

I certainly don't have any complaints :)
