### ISSUE TITLE
hostname does not get resolved

### ISSUE THREAD

**Issue by sysarcher** [AntonioMeireles/ClearLinux-packer#9]
OS: Linux (Ubuntu 16.04)
Provider: Virtualbox

While starting up the latest box `vagrant up` fails at setting hostname. This problem is not observed in boxes that are around 2 weeks old. Provisioning of the box doesn't happen.

`vagrant ssh` works but the hostname is some long random string.

**Comment by AntonioMeireles** [comment]
@shrmrf 

hi, 

this is odd, can you paste output of `vagrant plugin list` and contents of your `Vagrantfile`  please?

Thanks in advance

**Comment by sysarcher** [comment]
Hi Antonio..
I wasn't able to replicate this on my machine at home... Maybe this had something to do with corporate proxies etc.?? I'll let you know tomorrow/day after.

**Comment by AntonioMeireles** [comment]
ok, good to confirm that it's not a general issue. **Thanks**!

**Comment by AntonioMeireles** [comment]
@kvietmeier, 

*just in case*, can you double check on your side too, please 

**Thanks!**

**Comment by sysarcher** [comment]
Hello @AntonioMeireles 

I couldn't replicate the issue :(

Might've been some temporary issue with my machine... Sorry for the issue

Will close
